server:
  port: 65534
spring:
  datasource:
    url: jdbc:mysql://192.168.1.126:3307/test?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    password: root
    username: root
  redis:
    host: scrm-bus-redis
    password: ''
    port: 6369
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  global-config:
    banner: false
    db-config:
      id-type: auto
      insert-strategy: not_empty
      update-strategy: not_empty
      logic-delete-value: "NOW()" # 逻辑已删除值(使用当前时间标识)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
again:
  starter:
    es:
      host: scrm-bus-es
      port: 9100
      port1: 9101
      port2: 9102
      tcp_port: 9400
      tcp_port1: 9500
      tcp_port2: 9600
      cluster_name: scrm-es
      user_name:
      password:
  redis:
    key-prefix: 'wsn:bus:'